#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../bin/libfelt.{}.{}.framework/libfelt.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "../bin/libfelt{}{}".format(env["suffix"], env["SHLIBSUFFIX"]).replace("template_", ""),
        source=sources,
    )

Default(library)
